#!/usr/bin/env zsh
# shellcheck shell=sh

git_dir() {
  git rev-parse --is-inside-work-tree >/dev/null 2>&1
}

git_branch() {
  git symbolic-ref --short HEAD 2>/dev/null || git rev-parse --short HEAD 2>/dev/null
}

git_status() {
  git status --short 2>/dev/null
}

if git_dir ; then
  if [ -z "$(git_status)" ]; then
    print "%F{green}($(git_branch))%f "
  else
    print "%F{yellow}($(git_branch))%f "
  fi
fi
