#!/usr/bin/env zsh
# shellcheck shell=sh

if [ -n "$GEM_HOME" ]; then
  if [ ! -s "$GEM_HOME" ]; then
    print "%F{red}(${GEM_HOME#$HOME/.rvm/gems/})%f "
  else
    print "%B%F{black}(${GEM_HOME#$HOME/.rvm/gems/})%f%b "
  fi
fi
